name: Python Lint

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 requests ratelimit unidecode

    - name: Create .pylintrc file
      run: |
        echo "[MESSAGES CONTROL]" > .pylintrc
        echo "disable=duplicate-code" >> .pylintrc

    - name: Run pylint
      run: |
        pylint **/*.py

    - name: Run flake8
      run: |
        find . -name "*.py" | xargs flake8
